# Generated by Django 2.1.5 on 2019-04-29 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_post10_post11_post12_post13_post14_post15_post16_post17_post18_post19_post2_post3_post4_post5_post6_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
